Writers:
  groupname: Writers
  readableName: Writers
  description: 'Writers of the documentation'
  icon: pen
  access:
    admin:
      super: 'false'
      login: 'false'
      cache: 'false'
      configuration: 'false'
      configuration_system: 'false'
      configuration_site: 'false'
      configuration_media: 'false'
      configuration_info: 'false'
      settings: 'false'
      pages: 'true'
      maintenance: 'false'
      statistics: 'false'
      plugins: 'false'
      themes: 'false'
      users: 'false'
    admin-addon-user-manager:
      users: 'false'
      groups: 'false'
      users_expert: 'false'
Administrators:
  groupname: Administrators
  access:
    admin: {  }
    admin-addon-user-manager: {  }
