enabled: true
top_level_version: false
show_all_pages: false
home_url: 'localhost:8080'
github:
  position: 'off'
  tree: 'https://github.com/getgrav/grav-skeleton-rtfm-site/blob/develop/'
  commits: 'https://github.com/getgrav/grav-skeleton-rtfm-site/commits/develop/'
