enabled: true
navbar:
  sticky:
    enabled: true
searchPlaceHolder: 'Search the Library'
blogContinueText: 'Continue Reading...'
daringLinkIcon: exclamation-circle
animateOnPageLoad: false
streams:
  scheme:
    theme:
      type: ReadOnlyStream
      paths:
        - user/themes/library
dropdown:
  enabled: true
